Algoritmo "Faixa"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/04/2022
Var
 n:real

Inicio
 escreval ("digite um numero")
 leia (n)

 se (n>1) e (n<9) entao

 escreval ("esta na faixa")
 senão

 escreval ("não esta na faixa")

 fimse
Fimalgoritmo