Algoritmo "numero_imprimir"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/04/2022
Var
     n:inteiro


Inicio
      escreval ("digite um numero")
      leia (n)
      
      escreval (n)
      


Fimalgoritmo