Algoritmo "Quente"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/04/2022
Var

 n:real

Inicio
 escreval ("digite um número")
 leia (n)

 se (n >26) entao
 escreval ("esta um dia quente")
 senão
 escreval ("hoje não esta um dia quente")

    fimse

Fimalgoritmo